When logging, spit output to stderr when the program fails.

diff --git a/bin/common b/bin/common
--- a/bin/common
+++ b/bin/common
@@ -96,16 +96,38 @@ log()
 
     echo "START ${TAG} at $(date)" > "${OUT_LOG}"
     echo >> "${OUT_LOG}"
+    echo "Running $@" >> "${OUT_LOG}"
+    echo >> "${OUT_LOG}"
 
     if [ -t 1 ]
     then
-	"$@" 2>&1 | tee -a "${OUT_LOG}"
+
+	# Build the output separately because the shell doesn't always flush.
+	LOG_BUILD="${HOLE}.$$.build"
+
+	# Exit status catcher from
+        # https://unix.stackexchange.com/a/70675/15184
+	(((("$@" 2>&1 ; echo $? >&3) | tee "${LOG_BUILD}" >&4) 3>&1) | (read xs; exit $xs)) 4>&1
+	STATUS=$?
+	PRODUCE_ON_STDERR=false
+
+        cat "${LOG_BUILD}" >> "${OUT_LOG}"
+	rm -f "${LOG_BUILD}"
+
     else
-	"$@" 2>&1 | cat >> "${OUT_LOG}"
+
+	"$@" 2>&1 >> "${OUT_LOG}"
+	STATUS=$?
+	PRODUCE_ON_STDERR=true
+
     fi
 
     echo >> "${OUT_LOG}"
+    echo "Exited ${STATUS}" >> "${OUT_LOG}"
+    echo >> "${OUT_LOG}"
     echo "END ${TAG} at $(date)" >> "${OUT_LOG}"
+
+    ${PRODUCE_ON_STDERR} && cat "${OUT_LOG}" 1>&2
 }
 
 
